### PR TITLE
Bump deps

### PR DESCRIPTION
**Pull request by justaugustus**
#### What type of PR is this?

/kind cleanup
/area dependency

#### What this PR does / why we need it:

Needed for https://github.com/kubernetes-sigs/bom/pull/1.

#### Does this PR introduce a user-facing change?

```release-note

```

### CODE REVIEW

**Comment by justaugustus** [comment]
@cpanato -- want to take over my branch here, since you're already working on fixes?

**Comment by cpanato** [comment]
> @cpanato -- want to take over my branch here, since you're already working on fixes?

Sure thing, will push updates tomorrow

**Comment by cpanato** [comment]
all green now!

/assign @saschagrunert @Verolop @xmudrii @palnabarun 

after this we can cut a release

**Review by xmudrii — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
