### PR TITLE
go.mod: Use uwu-tools/magex

### PR DESCRIPTION
**Pull request by justaugustus**
#### What type of PR is this?

/kind cleanup
/area dependency

#### What this PR does / why we need it:

- go.mod: Use uwu-tools/magex (ref: https://github.com/uwu-tools/magex/releases/tag/v0.10.0)
- go.mod: Update github.com/uwu-tools/magex to v0.10.0

Signed-off-by: Stephen Augustus <foo@auggie.dev>

/assign @jeremyrickard @cpanato 
cc: @kubernetes-sigs/release-engineering 

#### Does this PR introduce a user-facing change?

```release-note
- go.mod: Use uwu-tools/magex (ref: https://github.com/uwu-tools/magex/releases/tag/v0.10.0)
- go.mod: Update github.com/uwu-tools/magex to v0.10.0
```

### CODE REVIEW

**Comment by justaugustus** [comment]
@kubernetes-sigs/release-engineering -- We need to do similar updates to our other projects; can I ask someone to work on this?

- https://github.com/kubernetes-sigs/bom
- https://github.com/kubernetes-sigs/release-sdk
- https://github.com/kubernetes-sigs/tejolote/blob

ref: https://cs.k8s.io/?q=carolynvs%2Fmagex&i=nope&files=&excludeFiles=&repos=

**Review by saschagrunert — APPROVED** [review]

**Comment by cpanato** [comment]
> @kubernetes-sigs/release-engineering -- We need to do similar updates to our other projects; can I ask someone to work on this?
> 
> 
> 
> - https://github.com/kubernetes-sigs/bom
> 
> - https://github.com/kubernetes-sigs/release-sdk
> 
> - https://github.com/kubernetes-sigs/tejolote/blob
> 
> 
> 
> ref: https://cs.k8s.io/?q=carolynvs%2Fmagex&i=nope&files=&excludeFiles=&repos=

Will do

**Comment by cpanato** [comment]
> @kubernetes-sigs/release-engineering -- We need to do similar updates to our other projects; can I ask someone to work on this?
> 
> * https://github.com/kubernetes-sigs/bom
> * https://github.com/kubernetes-sigs/release-sdk
> * https://github.com/kubernetes-sigs/tejolote/blob
> 
> ref: https://cs.k8s.io/?q=carolynvs%2Fmagex&i=nope&files=&excludeFiles=&repos=

all done

**Comment by justaugustus** [comment]
> all done

Thanks so much, @cpanato!!

**Pull request merged**
