### PR TITLE
Add new throttler pkg forked from nozzle/throttler

### PR DESCRIPTION
**Pull request by puerco**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:

This commit imports a fork of the [nozzle/throttler](https://github.com/nozzle/throttler) package. 

As discussed in https://github.com/kubernetes-sigs/release-utils/pull/107, this package is used in the release engineering tooling but has not had new commits in over six years so the release engineering team chose to adopt it to keep maintaining it.

#### Which issue(s) this PR fixes:

Follow-up to #107

#### Special notes for your reviewer:

I've imported the full commit history and added notices crediting the original package source and origin.

I also fixed the linter and updated the tests a little bit but they still need some improvement.

/cc @saschagrunert @xmudrii 

#### Does this PR introduce a user-facing change?

```release-note
- release-utils now has a new throttle package forked from nozzle/throttle
```

### CODE REVIEW

**Review by saschagrunert — APPROVED** [review]

**Comment by derekperkins** [comment]
Not a big deal that you forked it, just surprising that you didn't file an issue first. There hasn't been a compelling reason for us to make any changes, so it wasn't unmaintained or abandoned, just considered complete, barring issue reports.

**Comment by puerco** [comment]
Hey @derekperkins thanks for chiming in! 

I'm sorry, [in the rush to get another feature in we didn't think this through](https://github.com/kubernetes-sigs/release-utils/pull/107#discussion_r1686066576).  We should have filed an issue especially since we've been using the module for years, I'm happy to revert and we can contribute any patches back to you in the future. Apologies!

**Comment by puerco** [comment]
OK, opened https://github.com/kubernetes-sigs/release-utils/pull/111 to revert the fork!

**Comment by derekperkins** [comment]
No worries, really not a big deal either way. If anything, it was an ego booster that it was important enough to fork :)

I saw a few tweaked commits in this PR too that we're happy to pull in upstream, along with any other feedback you have.

**Pull request merged**
